[technote]
id = "RTN-113"
series_id = "RTN"
canonical_url = "https://rtn-113.lsst.io"
github_url = "https://github.com/lsst/rtn-113"
github_default_branch = "main"
date_created = 2026-01-16T15:45:07Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Christina L."
name.family = "Adair"
internal_id = "adaircl"
orcid = "https://orcid.org/0009-0008-8623-871X"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "Menlo Park"

[[technote.authors]]
name.given = "Sharon E."
name.family = "Hunt"
internal_id = "huntsh"
orcid = "https://orcid.org/0000-0002-5858-2002"
[[technote.authors.affiliations]]
name = "NSF NOIRLab"
internal_id = "NOIRLab"
address = "Tucson"

